Add tool to download the attachments from sqlite3 using wget instead of trac-admin
mavam/trac-hub pull request #22
Opened 2018-04-02 04:43 UTC by aerostitch

It's the equivalent from the mysql one.
Allows to do the download from a remote server with just a copy of the sqlite3 db.

2018-04-02 12:28 UTC, mavam requested changes
Thanks for the contribution!

I only have some minor syntactic change requests.

2018-04-02 12:28 UTC, mavam commented on tools/download-trac-attachment-sqlite3.sh
> +  if [[ $ticket == id ]]; then
Just a nit: I'm a big fan of POSIX shell scripts. If you change this to `[ "$ticket" = "id" ]` it'll be more portable.

2018-04-02 12:28 UTC, mavam commented on tools/download-trac-attachment-sqlite3.sh
> +  mkdir -p ${OUTPUT_DIR}/${ticket}
The argument to `mkdir` should be wrapped into double-quotes. You do this already below. :-)

2018-04-02 15:06 UTC, aerostitch commented
Thanks a lot for the review (and the other merges)!
I just pushed the new version with the changes.

2018-04-03 09:05 UTC, mavam approved these changes

2018-04-03 09:05 UTC, merged

2018-04-03 09:05 UTC, mavam commented
And thank you for all the work of putting together these great PRs! ❤️