Assigning GitHub Issue based on Trac's ticket owner and username mapping
mavam/trac-hub pull request #33
Opened 2021-01-25 23:50 UTC by soccerjoshj07

I liked that this tool supported using the Issue Import API's to allow for original creation time date/time stamps, but I was disappointed that it didn't carry through the Trac Owner --> GitHub Issue Assignee - this is my implementation of this.

* If Trac-->GitHub username mapping exists, use it where Trac ticket owner is mapped to GitHub Issue Assignee. 

* Added a note in the config to remind people to make sure not to typo their GitHub username mappings - an issue will fail to create if a mapping is found but the GitHub user does not exist:
```ruby
# make sure not to typo the GitHub username as the issue will fail to create if a ticket's owner (assignee) has a valid mapping below
```

* I also removed the GitHub Users login / old github username mapping content in the reaadme.

A potential improvement idea would be to use the GitHub user API to validate that a user is valid before continuing with the migration - this should be used by both github issue assignee AND the Issue body / comments - If you migrate with an invalid mapping in the non-forked code, their will be a `@username` in the issue body that does not reference a GitHub user, therefore it is not a link and just plain text.

2021-01-26 19:34 UTC, mavam requested changes
Thanks for the contribution!

I don't have a trac deployment to play with at the moment, so I cannot test the changes. However, based on the semantics of the proposed changes, I shuffled the code a bit around, which in my opinion simplifies the control flow a bit. Could you give it shot whether this still works? I'd be happy to merge them in that case.

2021-01-26 19:34 UTC, mavam commented on trac-hub
> +    end
```suggestion
    issue = {
      "title" => ticket[:summary],
      "body" => body,
      "labels" => labels.to_a,
      "closed" => ticket[:status] == "closed",
      "created_at" => format_time(ticket[:time]),
    }
    if @users.has_key?(owner)
      owner = trac_mail(ticket[:owner])
      github_owner = @users[owner]
      $logger.debug("..owner in trac: #{owner}")
      $logger.debug("..assignee in GitHub: #{github_owner}")
      issue["assignee"] = github_owner
    end
```

2021-01-26 22:53 UTC, soccerjoshj07 commented
That worked perfectly with a small modification to the if statement - `owner` was being referenced before being set :) 

https://github.com/mavam/trac-hub/pull/33/commits/e83ae0c6fbbf62c343c0d8e092cd797b62b0dc79

2021-01-27 06:03 UTC, mavam approved these changes

2021-01-27 06:03 UTC, merged